### ISSUE TITLE
Add coverage reports using codecov

### ISSUE THREAD

**Issue by matthew-palmer** [matthew-palmer/osrs_highscores#12]
Implement codecov.io Scanning into repository, example report format below:
Once implemented, a proper badge showing coverage should also be added to the README of project for at-a-glance reporting.

```yaml
script:
  - coverage run tests.py
# Push the results back to codecov
after_success:
  - codecov
```
